/* ============================================================
   Booking_Engagement_Analysis.sas
   Booking.com Social Media Engagement Study  v1.0.0
   2026-03-28

   Purpose: Academic-grade statistical analysis for the paper
            "How Textual Features Influence Social Media Engagement:
             Evidence from Booking.com on X"

   Input CSV: sas_ready.csv  (generated by run_statistics.py)
   ─────────────────────────────────────────────────────────────
   Variables in sas_ready.csv
     obs          – observation number (1..766)
     engagement   – raw DV: like + comment + share
     log_engage   – log(1 + engagement)   [primary DV in models]
     length       – text length (word count)       [H1, main IV]
     question     – question mark dummy (0/1)       [H2, main IV]
     valence      – emotional valence score         [H3, main IV]
     hashtag      – number of hashtags              [H4, main IV]
     picture      – number of pictures     [control]
     url          – number of URLs         [control]
     at_mention   – number of @mentions    [control]
     emoji        – number of emoji        [extension IV]
   ============================================================ */

/* ── 0. Set paths ─────────────────────────────────────────── */
/*
   sas_ready.csv is located at:  analysis/sas/input/sas_ready.csv
   SAS does not use relative paths — set the full absolute path below.
   Example (Linux / SAS Studio):
     %LET datapath = /workspaces/mkt2026group/analysis/sas/input/sas_ready.csv;
   Example (Windows):
     %LET datapath = C:\projects\mkt2026group\analysis\sas\input\sas_ready.csv;
*/
%LET datapath = /workspaces/mkt2026group/analysis/sas/input/sas_ready.csv;
/* Output folder for ODS reports (optional, leave empty to suppress) */
%LET outpath  = ;

OPTIONS NODATE NONUMBER LS=120 PS=60;

/* ── 1. Import CSV ────────────────────────────────────────── */
PROC IMPORT
    DATAFILE  = "&datapath"
    OUT       = work.engage
    DBMS      = CSV
    REPLACE;
    GETNAMES  = YES;
    GUESSINGROWS = MAX;
RUN;

/* Verify import */
TITLE "Data Preview — First 10 Observations";
PROC PRINT DATA=work.engage(OBS=10); RUN;
TITLE;

/* ── 2. Descriptive Statistics ────────────────────────────── */
/*
   PROC MEANS gives N, Mean, SD, Min, Max, Median, Skewness, Kurtosis.
   This is the standard "Table 2 – Descriptive Statistics" for papers.
*/
TITLE "Table 1. Descriptive Statistics";
PROC MEANS DATA=work.engage
    N MEAN STD MIN P25 MEDIAN P75 MAX SKEWNESS KURTOSIS
    MAXDEC=4;
    VAR engagement log_engage length question valence
        hashtag picture url at_mention emoji;
    LABEL
        engagement   = "Engagement (raw)"
        log_engage   = "log(1+Engagement)"
        length       = "Text Length (words)"
        question     = "Question Mark (0/1)"
        valence      = "Emotional Valence"
        hashtag      = "Hashtag Count"
        picture      = "Picture Count"
        url          = "URL Count"
        at_mention   = "At-Mention Count"
        emoji        = "Emoji Count";
RUN;
TITLE;

/* Frequency table for the dummy variable */
TITLE "Table 1b. Question Mark — Frequency Distribution";
PROC FREQ DATA=work.engage;
    TABLES question / NOCUM;
    LABEL question = "Question Mark (0=No, 1=Yes)";
RUN;
TITLE;

/* ── 3. Pearson Correlation Matrix ───────────────────────── */
/*
   Standard "Table 3 – Correlation Matrix" for academic papers.
   PROC CORR prints r and p-values; SINGP option marks significance.
*/
TITLE "Table 2. Pearson Correlation Matrix";
PROC CORR DATA=work.engage
    NOSIMPLE          /* suppress individual var stats (shown above) */
    NOPROB;           /* suppress individual p-values inline —
                         remove NOPROB to show p below each r        */
    VAR log_engage length question valence hashtag
        picture url at_mention emoji;
    LABEL
        log_engage   = "log(1+Engagement)"
        length       = "Text Length"
        question     = "Question Mark"
        valence      = "Emotional Valence"
        hashtag      = "Hashtag"
        picture      = "Picture"
        url          = "URL"
        at_mention   = "At-Mention"
        emoji        = "Emoji";
RUN;
TITLE;

/* Version with p-values (useful for selecting significance stars) */
TITLE "Table 2b. Pearson Correlation Matrix (with p-values)";
PROC CORR DATA=work.engage NOSIMPLE;
    VAR log_engage length question valence hashtag
        picture url at_mention emoji;
RUN;
TITLE;

/* ── 4. OLS Regression ───────────────────────────────────── */

/* ── Model 1: Baseline — H1 to H4 + Controls ─────────────── */
TITLE "Table 3. OLS Regression — Model 1: Baseline";
PROC REG DATA=work.engage PLOTS=NONE;
    MODEL log_engage = length question valence hashtag
                       picture url at_mention
          / STB       /* standardised beta coefficients   */
            VIF       /* Variance Inflation Factors       */
            CLB       /* 95% confidence intervals         */
            TOL;      /* Tolerance = 1/VIF                */
    LABEL
        log_engage = "DV: log(1+Engagement)"
        length     = "H1: Text Length"
        question   = "H2: Question Mark"
        valence    = "H3: Emotional Valence"
        hashtag    = "H4: Hashtag Count"
        picture    = "Picture (control)"
        url        = "URL (control)"
        at_mention = "At-Mention (control)";
    OUTPUT OUT=work.resid1
           PREDICTED=yhat1 RESIDUAL=e1 RSTUDENT=rstud1 H=leverage1;
RUN;
TITLE;

/* ── Model 2: Extension — + Emoji ───────────────────────── */
TITLE "Table 4. OLS Regression — Model 2: Extension (+Emoji)";
PROC REG DATA=work.engage PLOTS=NONE;
    MODEL log_engage = length question valence hashtag
                       picture url at_mention emoji
          / STB VIF CLB TOL;
    LABEL
        log_engage = "DV: log(1+Engagement)"
        length     = "H1: Text Length"
        question   = "H2: Question Mark"
        valence    = "H3: Emotional Valence"
        hashtag    = "H4: Hashtag Count"
        picture    = "Picture (control)"
        url        = "URL (control)"
        at_mention = "At-Mention (control)"
        emoji      = "Emoji (extension)";
    OUTPUT OUT=work.resid2
           PREDICTED=yhat2 RESIDUAL=e2 RSTUDENT=rstud2 H=leverage2;
RUN;
TITLE;

/* ── 5. Residual Diagnostics (Model 1) ───────────────────── */
/* Normality of residuals */
TITLE "Table 5. Residual Normality Test — Model 1 (Shapiro-Wilk)";
PROC UNIVARIATE DATA=work.resid1 NORMAL;
    VAR e1;
    HISTOGRAM e1 / NORMAL;
    QQPLOT    e1 / NORMAL(MU=EST SIGMA=EST);
RUN;
TITLE;

/* Breusch-Pagan heteroscedasticity — approximate via REG on e1^2 */
DATA work.resid1_sq;
    SET work.resid1;
    e1_sq = e1**2;
RUN;
TITLE "Table 5b. Heteroscedasticity Check — Breusch-Pagan Approximation";
PROC REG DATA=work.resid1_sq PLOTS=NONE;
    MODEL e1_sq = length question valence hashtag
                  picture url at_mention;
    /* Significant overall F → evidence of heteroscedasticity */
RUN;
TITLE;

/* ── 6. Robust Standard Errors (HC3) via PROC SURVEYREG ─── */
/*
   PROC SURVEYREG with VARMETHOD=TAYLOR gives
   heteroscedasticity-consistent (HC) standard errors,
   which is the robust SE approach preferred in papers.
*/
TITLE "Table 6. Robust OLS — Model 1 (HC Standard Errors)";
PROC SURVEYREG DATA=work.engage VARMETHOD=TAYLOR;
    MODEL log_engage = length question valence hashtag
                       picture url at_mention / SOLUTION;
RUN;
TITLE;

TITLE "Table 6b. Robust OLS — Model 2 (HC Standard Errors)";
PROC SURVEYREG DATA=work.engage VARMETHOD=TAYLOR;
    MODEL log_engage = length question valence hashtag
                       picture url at_mention emoji / SOLUTION;
RUN;
TITLE;

/* ── 7. Model Comparison (F-test: M2 vs M1) ─────────────── */
/*
   Test whether adding emoji significantly improves fit.
   Done manually: Δ R² F-test.
*/
TITLE "Supplementary: Δ R² Comparison — Model 1 vs Model 2";
PROC REG DATA=work.engage PLOTS=NONE;
    M1: MODEL log_engage = length question valence hashtag
                           picture url at_mention;
    M2: MODEL log_engage = length question valence hashtag
                           picture url at_mention emoji;
    /* Compare by reading R² and F statistics from each */
RUN;
TITLE;

/* ── 8. Optional: Subgroup mean comparison (question=0 vs 1) */
TITLE "Table 7. Mean Engagement by Question Mark (t-test)";
PROC TTEST DATA=work.engage;
    CLASS   question;
    VAR     log_engage engagement;
RUN;
TITLE;

/* ── 9. Summary note ─────────────────────────────────────── */
%PUT ==================================================;
%PUT  Booking.com Engagement Analysis  v1.0.0  DONE;
%PUT  Models 1 & 2 estimated. Check log for warnings.;
%PUT ==================================================;

/* ============================================================
   HOW TO USE THIS FILE
   ─────────────────────────────────────────────────────────────
   1. Run `python analysis/python/run_statistics.py` to generate
        analysis/sas/input/sas_ready.csv
   2. Update %LET datapath (line ~28) to the full absolute path
        of sas_ready.csv on your machine / SAS environment
   3. Open SAS and submit this file, OR run via batch:
        sas Booking_Engagement_Analysis.sas
   4. Key tables for the paper:
        Table 1  → PROC MEANS output  (Descriptive Statistics)
        Table 2  → PROC CORR output   (Correlation Matrix)
        Table 3  → Model 1 PROC REG   (Baseline OLS)
        Table 4  → Model 2 PROC REG   (Extension OLS)
        Table 5  → PROC UNIVARIATE    (Residual diagnostics)
        Table 6  → PROC SURVEYREG     (Robust SE)
   5. SAS output files go in: analysis/sas/output/
   ============================================================ */
